// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_tvdenoising_RCPPEXPORTS_H_GEN_
#define RCPP_tvdenoising_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace tvdenoising {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("tvdenoising", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("tvdenoising", "_tvdenoising_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in tvdenoising");
            }
        }
    }

    inline NumericVector flsa_dp(NumericVector y, double lambda) {
        typedef SEXP(*Ptr_flsa_dp)(SEXP,SEXP);
        static Ptr_flsa_dp p_flsa_dp = NULL;
        if (p_flsa_dp == NULL) {
            validateSignature("NumericVector(*flsa_dp)(NumericVector,double)");
            p_flsa_dp = (Ptr_flsa_dp)R_GetCCallable("tvdenoising", "_tvdenoising_flsa_dp");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_flsa_dp(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(lambda)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

    inline NumericVector flsa_dp_weighted(NumericVector y, double lambda, NumericVector weights) {
        typedef SEXP(*Ptr_flsa_dp_weighted)(SEXP,SEXP,SEXP);
        static Ptr_flsa_dp_weighted p_flsa_dp_weighted = NULL;
        if (p_flsa_dp_weighted == NULL) {
            validateSignature("NumericVector(*flsa_dp_weighted)(NumericVector,double,NumericVector)");
            p_flsa_dp_weighted = (Ptr_flsa_dp_weighted)R_GetCCallable("tvdenoising", "_tvdenoising_flsa_dp_weighted");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_flsa_dp_weighted(Shield<SEXP>(Rcpp::wrap(y)), Shield<SEXP>(Rcpp::wrap(lambda)), Shield<SEXP>(Rcpp::wrap(weights)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<NumericVector >(rcpp_result_gen);
    }

}

#endif // RCPP_tvdenoising_RCPPEXPORTS_H_GEN_
