// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flsa_dp
NumericVector flsa_dp(NumericVector y, double lambda);
RcppExport SEXP _tvdenoising_flsa_dp(SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(flsa_dp(y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// flsa_dp_weighted
NumericVector flsa_dp_weighted(NumericVector y, double lambda, NumericVector weights);
RcppExport SEXP _tvdenoising_flsa_dp_weighted(SEXP ySEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(flsa_dp_weighted(y, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tvdenoising_flsa_dp", (DL_FUNC) &_tvdenoising_flsa_dp, 2},
    {"_tvdenoising_flsa_dp_weighted", (DL_FUNC) &_tvdenoising_flsa_dp_weighted, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tvdenoising(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
