# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_tvd <- function(y, lambda) {
    .Call('_tvdenoising_rcpp_tvd', PACKAGE = 'tvdenoising', y, lambda)
}

rcpp_wtvd <- function(y, lambda, weights) {
    .Call('_tvdenoising_rcpp_wtvd', PACKAGE = 'tvdenoising', y, lambda, weights)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_tvdenoising_RcppExport_registerCCallable', PACKAGE = 'tvdenoising')
})
