# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Univariate total variation denoising
#'
#' Total variation denoising is performed at a fixed tuning parameter value
#' using the linear-time dynamic programming approach of Johnson (2013).
#'
#' @param y Numeric vector of observations.
#' @param lambda Regularization parameter.
#' @return Numeric vector of the same length as y, containing denoised
#' 	observations.
flsa_dp <- function(y, lambda) {
    .Call('_tvdenoising_flsa_dp', PACKAGE = 'tvdenoising', y, lambda)
}

#' Weighted univariate total variation denoising
#'
#' Total variation denoising is performed at a fixed tuning parameter
#' value using the linear-time dynamic programming approach of Johnson
#' (2013), subject to observation weights
#'
#' @param y Numeric vector of observations.
#' @param lambda Regularization parameter.
#' @param weights Numeric vector of the same length as y, containing
#'		observation weights.
#' @return Numeric vector of the same length as y, containing denoised
#' 	observations.
flsa_dp_weighted <- function(y, lambda, weights) {
    .Call('_tvdenoising_flsa_dp_weighted', PACKAGE = 'tvdenoising', y, lambda, weights)
}

